version: "3.9"
services:
  prefect-worker:
    build:
      context: ..
      dockerfile: prefect/Dockerfile
    image: custom-prefect-worker:3.6.13-python3.12
    container_name: prefect_worker
    restart: always
    volumes:
      # Lembre-se: No outro PC, essas pastas devem existir e ter o código atualizado!
      - ../flows_prefect:/app/flows_prefect
      - ../dbt_projects:/app/dbt_projects
    command: >
      sh -c "sleep 5 && 
            prefect work-pool create --type process 'process-pool' || true && 
            prefect worker start --pool 'process-pool'"
    environment:
      # 🔴 MUDANÇA CRÍTICA AQUI 🔴
      # Se estiver no mesmo PC (e mesma rede docker): http://prefect-server:4200/api
      # Se estiver em OUTRO PC: Troque pelo IP da Máquina A (ex: 192.168.21.X)
      - PREFECT_API_URL=http://host.docker.internal:4200/api
    
    # 'depends_on' foi removido porque o server não está neste arquivo