services:
  prefect-worker:
    image: custom-prefect-worker:3.6.13-python3.12
    build:
      context: ..                       
      dockerfile: prefect-worker/Dockerfile
    restart: always
    volumes:
      - ../:/app
    env_file:
      - .env.worker
    environment:
      - PYTHONPATH=/app:/app/flows_prefect:/app/tasks_python
      - PREFECT_API_URL=http://192.168.21.251:4200/api
      # ADICIONE ISTO para os logs ficarem no horário de Brasília
      - TZ=America/Sao_Paulo              # <--- 
    command: >
      sh -c "
        sleep 10 &&
        prefect work-pool create --type process process-pool --overwrite || true &&
        python /app/_ops/deploy_all.py &&
        prefect worker start --pool process-pool --work-queue default --limit 3 --name $${WORKER_NAME}
      "