services:
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:25.2.0
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    volumes:
      - ./dremio_data:/opt/dremio/data

networks:
  default:
    driver: bridge
