version: 2

# definindo a conexão com a BRONZE
sources:
  # Apenas Bronze como documentação
  - name: bronze
    schema: main
    tables:
      - name: compras_acode
        description: "Arquivos Parquet brutos do bucket Bronze. (Lido via read_parquet na Silver)"
        # A parte 'external' abaixo não é obrigatória já que estamos lendo direto, 
        # mas serve para você lembrar onde os arquivos estão se olhar só o YAML.
        external:
          location: "s3://bronze/compras-acode/**/*.parquet"

# Definindo regras para manter a qualidade dos dados da silver
models:
  - name: silver_acode_compras_produto_comercial
    description: "Tabela consolidada de compras, limpa e tipada para o DuckDB"
    columns:
      - name: EAN
        description: "Código EAN do produto"
        data_tests:
          - not_null

      - name: Loja_CNPJ
        description: "CNPJ da loja emissora"
        data_tests:
          - not_null

      - name: data_emissao
        description: "Data da emissão da nota"
        data_tests:
          - not_null

      - name: Val_Prod_sem_STRet
        description: "Valor do produto sem ST Retido"