services:
  postgres-database:
    image: postgres:15-alpine
    container_name: prefect_db
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect
    volumes:
      - ./db_prefect:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d prefect"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect-server:
    image: prefecthq/prefect:3.6.13-python3.12
    container_name: prefect_server
    restart: always
    ports:
      - "4200:4200"
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0"]
    environment:
      # Conexão interna com o banco (funciona pois estão no mesmo arquivo)
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres-database:5432/prefect
      
      # IMPORTANTE: Se for acessar de outros PCs, coloque o IP DA MÁQUINA aqui, não localhost
      # Ex: http://192.168.0.10:4200/api
      - PREFECT_UI_API_URL=http://localhost:4200/api 
      
      - PREFECT_SERVER_API_HOST=0.0.0.0
    depends_on:
      postgres-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://127.0.0.1:4200/api/health\")'"]
      interval: 10s
      timeout: 5s
      retries: 5