name: 'dbt_projetos'
version: '1.0.0'
config-version: 2

on-run-start: 
  - "{{ prevent_full_run() }}" # prevenção contra run de todos os .sql
  - "USE REFERENCE main IN nessie"

profile: 'dbt_projetos'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# CONFIGURAÇÃO DOS MODELOS
models:
  dbt_projetos:
    # Configurações globais (opcional)
    +materialized: view 

    desativados:        
      +enabled: false   # O '+' desliga tudo lá dentro