dbt_projetos:
  target: dev
  outputs:
    dev:
      type: dremio
      software_host: 192.168.21.124
      port: 9047
      use_ssl: False                 # Essencial para conexões locais sem certificado
      user: inteligencia
      password: dremio123
      datalake: thrash
      database: thrash
  target: dev